package com.restocktime.monitor.config.model.notifications;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;

@JsonIgnoreProperties(ignoreUnknown = true)
@Data
public class SiteNotificationsConfig {
    private NotificationConfig adidas;
    private NotificationConfig bstn;
    private NotificationConfig endclothing;
    private NotificationConfig naked;
    private NotificationConfig offwhite;
    private NotificationConfig oneblockdown;
    private NotificationConfig porter;
    private NotificationConfig shopify;
    private NotificationConfig shopifykw;
    private NotificationConfig snkrs;
    private NotificationConfig snkrsGb;
    private NotificationConfig snkrsJp;
    private NotificationConfig snkrsCn;
    private NotificationConfig snkrsOther;
    private NotificationConfig solebox;
    private NotificationConfig ssense;
    private NotificationConfig svd;
    private NotificationConfig titolo;
    private NotificationConfig test;
    private NotificationConfig log;
    private NotificationConfig keyword;
    private NotificationConfig yme;
    private NotificationConfig barneys;
    private NotificationConfig supreme;
    private NotificationConfig toytokyo;
    private NotificationConfig target;
    private NotificationConfig hottopic;
    private NotificationConfig bhvideo;
    private NotificationConfig bestbuy;
    private NotificationConfig nikeScratch;
    private NotificationConfig nikeScratchGB;
    private NotificationConfig acronym;
    private NotificationConfig sjs;
    private NotificationConfig footdistrict;
    private NotificationConfig patta;
    private NotificationConfig thenextdoor;
    private NotificationConfig nittygritty;
    private NotificationConfig backdoor;
    private NotificationConfig frenzy;
    private NotificationConfig rimowa;
    private NotificationConfig antonioli;
    private NotificationConfig twitter;
    private NotificationConfig sns;
    private NotificationConfig complexcon;
    private NotificationConfig footpatrol;
    private NotificationConfig soto;
    private NotificationConfig citygear;
    private NotificationConfig supremeuk;
    private NotificationConfig ccs;
    private NotificationConfig jimmyjazz;
    private NotificationConfig demandware;
    private NotificationConfig walmart;
    private NotificationConfig lvr;
    private NotificationConfig ftlcodes;
    private NotificationConfig amazon;
    private NotificationConfig barnesandnoble;
    private NotificationConfig daveyboystoys;
    private NotificationConfig disney;
    private NotificationConfig funimation;
    private NotificationConfig fye;
    private NotificationConfig gamestop;
    private NotificationConfig gemini;
    private NotificationConfig popcultcha;
    private NotificationConfig walgreens;
    private NotificationConfig instagram;
    private NotificationConfig footsites;
    private NotificationConfig onygo;
    private NotificationConfig shoepalace;
    private NotificationConfig kith;
    private NotificationConfig bodega;
    private NotificationConfig undefeated;
    private NotificationConfig dsm;
    private NotificationConfig concepts;
    private NotificationConfig yeezysupply;
    private NotificationConfig travis;
    private NotificationConfig chinatown;
    private NotificationConfig offspring;
    private NotificationConfig nikeDesktop;
}
